### ISSUE TITLE
Can’t find libjpeg.so.8

### ISSUE THREAD

**Issue by nikhola** [etfdevs/ETe#102]
Hi,
I try to run ETe in Debian Sid (amd64).
I can’t compile it (see the other issue), thus I downloaded the binary.
Here is ETe’s output:
./ete.x86_64: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

I installed libjpeg 9 (amd64 and x86) but no way, even symlinked.
Yours,
nicolas

**Comment by ensiform** [comment]
Your system does not have libjpeg8 compatibility, therefore you'll need self compile using the bundled jpeg option

**Comment by nikhola** [comment]
On 08/12/2024 22:03:18, Ensiform wrote:

> Your system does not have libjpeg8 compatibility, therefore you'll
> need self compile using the bundled jpeg option

There is no backward compatibility between libjpeg9 and libjpeg8?
No way to use the latest libjpeg library?
Quake3 (ioquake3) runs fine on my system.

Yours,
nicolas

**Comment by ensiform** [comment]
You need v8 because v8 is linked to in the build system, once you fix your self build, you need to pass -DUSE_SYSTEM_JPEG=OFF before the .. in cmake line. 

Your system has libjpeg-turbo by default which is 6.2 ABI compatible not 8 or 9 and then you installed 9 which is also not 8 compatible. You would need to get the libjpeg8 package from https://archive.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8b-1_amd64.deb if you want to try the pre built currently. 

The only reason Quake3 (ioquake3) works is because it ships a bundled copy of libjpeg9 which I don't currently do as everyone except for Debian still has 8 compatibility in their repo.
