### ISSUE TITLE
Possible collision physics issue on unreleased etf_furious map

### ISSUE THREAD

**Issue by ensiform** [etfdevs/ETe#32]
See https://www.youtube.com/watch?v=qZKw_BpYLkk

**Comment by KuehnhammerTobias** [comment]
Hi, I just want to note that this bug is not ETe specific. It's a idtech3 bug that has been there since Q3A (1999). You can see this in q3tourney3 for example, and many, many other idtech3 maps. The problem occurs when you collide against a wall that is not 100% perpendicular. Simply put a cuboid clip brush over the obstacle.
Though, you are right it would be better to fix it by source code than by map geometry. Personally I never found a fix for it. Tremulous/Xreal fixed it iirc, by accident I think, because of their wall-climbing ability. Hmm..

**Comment by KuehnhammerTobias** [comment]
Yeah! You can reproduce this in any idtech3 game (at least I'm aware of). This means Q3, RtCW, ET and all mods and standalone games based upon it. Maybe I am wrong, but the only idtech3 game that don't behave this weird is Xreal (Tremulous pmove code), as already said.
You can even reproduce the issue in Jedi Academy. The map was called 'Yavin Training Arena' or something... You are more Jedi expert than me, but I think you know the map...
Maybe it is also worth noting that the issue is caused inside the pmove code imo (you can see this by making the bounding box visible if the game supports that (ET, Spearmint)), cgame suffers more or less depending on game. In Q3 games the effect (on the playermodel with cg_thirdperson 1) is more significant than in games >= RtCW. I don't know why, maybe because the different animation system?
Nevertheless, the bobbing of the bbox and the view shaking (cg_thirdperson 0) are equal for all games.

**Comment by ensiform** [comment]
Not sure if I should close or just reclassify and push lower. Its not really an issue since the map is unreleased and can eventually be worked around.
