### ISSUE TITLE
Server side wwwdl is borked

### ISSUE THREAD

**Issue by ensiform** [etfdevs/ETe#77]
Seems specific to after one download

**Comment by Aciz** [comment]
Did some testing on this.

Crash happens here on `MSG_WriteByte`, `data` is NULL
https://github.com/etfdevs/ETe/blob/73c0fd468bd418789ccf446f4f53d86531f71921/src/qcommon/msg.c#L275-L280

Server setup
* `sv_wwwBaseURL` set
* `sv_wwwFallbackURL` not set
* `sv_wwwdownload 1`

Client setup
* `cl_wwwdownload 1` 
* `cl_allowdownload 3`

The issue is specifically at the second time when wwwdl redirection happens. Weirdly enough this seems to only concern maps, and not mod binary downloads. Some test scenarios:

* Connect -> wwwdl map -> change map -> wwwdl map -> server crash
* Connect -> wwwdl map -> change map -> no wwwdl (map already downloaded) -> change map -> wwwdl map -> server crash
* Connect -> wwwdl 2 maps (forced downloads with .campaign files) -> server crash on 2nd pk3 download
* Connect -> wwwdl map -> 2nd client connect -> wwwdl same map -> no crash
* Connect -> wwwdl map -> 2nd client connect -> wwwdl mod, map exists -> no crash

This might be some sort of data race, as stepping through the functions in stack when the crash happens actually does not crash the server.

Stack + locals
![image](https://user-images.githubusercontent.com/14221121/191446768-0e924d8a-90af-47c1-8b80-2c0e0408fd80.png)

**Comment by ensiform** [comment]
Checked that UDP download isn't affected.

**Comment by ensiform** [comment]
Might be fixed in https://github.com/etfdevs/ETe/commit/48b1502708c2fa308ed1f4105d134afd43c8e69c

Waiting to close until more confirmation

**Comment by Aciz** [comment]
File handles seem to be left open after downloads finish, eventually leading to crash after enough downloads have been done.

![image](https://user-images.githubusercontent.com/14221121/210646323-71adc7fd-1c62-4f4a-943b-042fc693490e.png)

**Comment by Aciz** [comment]
Additional file handle gets opened for each download here
https://github.com/etfdevs/ETe/blob/48b1502708c2fa308ed1f4105d134afd43c8e69c/src/server/sv_client.c#L1415-L1417

This check fails, but the file never gets closed.
